tex.catwitherror: hopefully fix the formatting of errors which look ambiguous either because their size exceeds the value itself or because the value is shown with N digits while the error has N+x digits